version: '3.8'

services:
  sql_db:
    container_name: juridibase_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: "0:0"
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Upn_2026_Juridibase#
      - MSSQL_PID=Developer
    volumes:
      - mssql_data:/var/opt/mssql/data
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "Upn_2026_Juridibase#" -C -Q "SELECT 1" || exit 1
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 5s

  web_app:
    container_name: juridibase_web
    image: juridibase_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:8080"
    depends_on:
      sql_db:
        condition: service_healthy
    environment:
      - ConnectionStrings__CadenaSQL=Server=sql_db,1433;Database=DB_JURIDIBASE_MIGUELROJAS;User Id=sa;Password=Upn_2026_Juridibase#;TrustServerCertificate=True;

volumes:
  mssql_data:
