// <auto-generated />
using System;
using Abogados_MiguelRojas_JURIDIBASE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Abogados_MiguelRojas_JURIDIBASE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603224751_M4")]
    partial class M4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.Abogado", b =>
                {
                    b.Property<int>("idAbogado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idAbogado"));

                    b.Property<string>("apellidoAbogado")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("correoAbogado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("dniAbogado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("especialidadAbogado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("estadoAbogado")
                        .HasColumnType("bit");

                    b.Property<int>("id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("nombreAbogado")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("telefonoAbogado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idAbogado");

                    b.HasIndex("id_Usuario")
                        .IsUnique();

                    b.ToTable("abogados");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.AbogadoArea", b =>
                {
                    b.Property<int>("idAbogadoArea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idAbogadoArea"));

                    b.Property<int>("id_Abogado")
                        .HasColumnType("int");

                    b.Property<int>("id_AreaDerecho")
                        .HasColumnType("int");

                    b.HasKey("idAbogadoArea");

                    b.HasIndex("id_Abogado");

                    b.HasIndex("id_AreaDerecho");

                    b.ToTable("abogadoArea");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.AbogadoServicio", b =>
                {
                    b.Property<int>("idAbogadoServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idAbogadoServicio"));

                    b.Property<int>("id_Abogado")
                        .HasColumnType("int");

                    b.Property<int>("id_ServicioLegal")
                        .HasColumnType("int");

                    b.HasKey("idAbogadoServicio");

                    b.HasIndex("id_Abogado");

                    b.HasIndex("id_ServicioLegal");

                    b.ToTable("AbogadoServicio");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.AreaDerecho", b =>
                {
                    b.Property<int>("idAreaDerecho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idAreaDerecho"));

                    b.Property<string>("descripcionAreaDerecho")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("estadoAreaDerecho")
                        .HasColumnType("bit");

                    b.Property<string>("nombreAreaDerecho")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("idAreaDerecho");

                    b.ToTable("areasDerecho");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.Audiencia", b =>
                {
                    b.Property<int>("idAudiencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idAudiencia"));

                    b.Property<string>("direccionAudiencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("fechaAudiencia")
                        .HasColumnType("date");

                    b.Property<DateTime>("horaAudiencia")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_Abogado")
                        .HasColumnType("int");

                    b.Property<int>("id_Caso")
                        .HasColumnType("int");

                    b.Property<string>("linkAudiencia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("tipoAudiencia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("idAudiencia");

                    b.HasIndex("id_Abogado");

                    b.HasIndex("id_Caso");

                    b.ToTable("audiencia");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.Caso", b =>
                {
                    b.Property<int>("idCaso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCaso"));

                    b.Property<string>("descripcionCaso")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("estadoCaso")
                        .HasColumnType("bit");

                    b.Property<int>("id_Abogado")
                        .HasColumnType("int");

                    b.Property<int>("id_Cliente")
                        .HasColumnType("int");

                    b.Property<string>("tituloCaso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("idCaso");

                    b.HasIndex("id_Abogado");

                    b.HasIndex("id_Cliente");

                    b.ToTable("caso");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.Cita", b =>
                {
                    b.Property<int>("idCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCita"));

                    b.Property<string>("asuntoLegalCita")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("detallesAdicionalesCita")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("estadoCita")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("fechaHoraCita")
                        .HasColumnType("date");

                    b.Property<int>("id_Abogado")
                        .HasColumnType("int");

                    b.Property<int>("id_Cliente")
                        .HasColumnType("int");

                    b.HasKey("idCita");

                    b.HasIndex("id_Abogado");

                    b.HasIndex("id_Cliente");

                    b.ToTable("cita");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.Cliente", b =>
                {
                    b.Property<int>("idCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCliente"));

                    b.Property<string>("correoCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("descripcionCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccionCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("dniCliente")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<bool>("estadoCliente")
                        .HasColumnType("bit");

                    b.Property<int>("idAbogado")
                        .HasColumnType("int");

                    b.Property<string>("nombreCliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("rucCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefonoCliente")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("tipoCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCliente");

                    b.HasIndex("idAbogado");

                    b.ToTable("cliente");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.DocumentosLegales", b =>
                {
                    b.Property<int>("idDocumentoLegal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDocumentoLegal"));

                    b.Property<DateOnly>("fechaCreacion")
                        .HasColumnType("date");

                    b.Property<int>("id_Expediente")
                        .HasColumnType("int");

                    b.Property<string>("nombreDocumento")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("rutaDocumento")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("idDocumentoLegal");

                    b.HasIndex("id_Expediente");

                    b.ToTable("documento");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.Especialista", b =>
                {
                    b.Property<int>("idEspecialista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEspecialista"));

                    b.Property<string>("correoEspecialista")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("descripcionEspecialista")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("disponibilidadEspecialista")
                        .HasColumnType("bit");

                    b.Property<string>("dniEspecialista")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("estadoEspecialista")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("nombreEspecialista")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("telefonoEspecialista")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("idEspecialista");

                    b.ToTable("especialista");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.Expediente", b =>
                {
                    b.Property<int>("idExpediente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idExpediente"));

                    b.Property<bool>("estadoExpediente")
                        .HasColumnType("bit");

                    b.Property<string>("fechaCierre")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("fechaInicio")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("id_Caso")
                        .HasColumnType("int");

                    b.Property<string>("resumenExpediente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("tipoExpediente")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("tituloExpediente")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("victima")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("victimario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("idExpediente");

                    b.HasIndex("id_Caso")
                        .IsUnique();

                    b.ToTable("expediente");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.Notificacion", b =>
                {
                    b.Property<int>("idNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idNotificacion"));

                    b.Property<DateOnly>("fechaNotificacion")
                        .HasColumnType("date");

                    b.Property<int>("id_Usuario")
                        .HasColumnType("int");

                    b.Property<bool>("leido")
                        .HasColumnType("bit");

                    b.Property<string>("mensajeNotificacion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("tituloNotificacion")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("idNotificacion");

                    b.HasIndex("id_Usuario");

                    b.ToTable("notificacion");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.Pago", b =>
                {
                    b.Property<int>("idPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPago"));

                    b.Property<DateOnly>("fechaPago")
                        .HasColumnType("date");

                    b.Property<int>("idAbogado")
                        .HasColumnType("int");

                    b.Property<int>("idCliente")
                        .HasColumnType("int");

                    b.Property<int>("id_Caso")
                        .HasColumnType("int");

                    b.Property<string>("metodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("monto")
                        .HasColumnType("real");

                    b.HasKey("idPago");

                    b.HasIndex("idAbogado");

                    b.HasIndex("idCliente");

                    b.HasIndex("id_Caso");

                    b.ToTable("pago");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.ServicioLegal", b =>
                {
                    b.Property<int>("idServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idServicio"));

                    b.Property<float>("costoBase")
                        .HasColumnType("real");

                    b.Property<string>("descripcionServicio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("estadoServicio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nombreServicio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("idServicio");

                    b.ToTable("servicio");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.Usuario", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idUsuario"));

                    b.Property<string>("nombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("passwordUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("rolUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idUsuario");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.Abogado", b =>
                {
                    b.HasOne("Abogados_MiguelRojas_JURIDIBASE.Models.Usuario", "usuario")
                        .WithOne("abogado")
                        .HasForeignKey("Abogados_MiguelRojas_JURIDIBASE.Models.Abogado", "id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.AbogadoArea", b =>
                {
                    b.HasOne("Abogados_MiguelRojas_JURIDIBASE.Models.Abogado", "abogado")
                        .WithMany("abogadoArea")
                        .HasForeignKey("id_Abogado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Abogados_MiguelRojas_JURIDIBASE.Models.AreaDerecho", "areaDerecho")
                        .WithMany("abogadoArea")
                        .HasForeignKey("id_AreaDerecho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("abogado");

                    b.Navigation("areaDerecho");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.AbogadoServicio", b =>
                {
                    b.HasOne("Abogados_MiguelRojas_JURIDIBASE.Models.Abogado", "abogado")
                        .WithMany("abogadoServicio")
                        .HasForeignKey("id_Abogado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Abogados_MiguelRojas_JURIDIBASE.Models.ServicioLegal", "servicioLegal")
                        .WithMany("abogadoServicio")
                        .HasForeignKey("id_ServicioLegal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("abogado");

                    b.Navigation("servicioLegal");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.Audiencia", b =>
                {
                    b.HasOne("Abogados_MiguelRojas_JURIDIBASE.Models.Abogado", "abogado")
                        .WithMany("audiencia")
                        .HasForeignKey("id_Abogado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Abogados_MiguelRojas_JURIDIBASE.Models.Caso", "caso")
                        .WithMany("audiencia")
                        .HasForeignKey("id_Caso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("abogado");

                    b.Navigation("caso");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.Caso", b =>
                {
                    b.HasOne("Abogados_MiguelRojas_JURIDIBASE.Models.Abogado", "abogado")
                        .WithMany("caso")
                        .HasForeignKey("id_Abogado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Abogados_MiguelRojas_JURIDIBASE.Models.Cliente", "cliente")
                        .WithMany("caso")
                        .HasForeignKey("id_Cliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("abogado");

                    b.Navigation("cliente");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.Cita", b =>
                {
                    b.HasOne("Abogados_MiguelRojas_JURIDIBASE.Models.Abogado", "abogado")
                        .WithMany("cita")
                        .HasForeignKey("id_Abogado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Abogados_MiguelRojas_JURIDIBASE.Models.Cliente", "cliente")
                        .WithMany("cita")
                        .HasForeignKey("id_Cliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("abogado");

                    b.Navigation("cliente");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.Cliente", b =>
                {
                    b.HasOne("Abogados_MiguelRojas_JURIDIBASE.Models.Abogado", "abogado")
                        .WithMany("cliente")
                        .HasForeignKey("idAbogado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("abogado");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.DocumentosLegales", b =>
                {
                    b.HasOne("Abogados_MiguelRojas_JURIDIBASE.Models.Expediente", "expediente")
                        .WithMany("documentosLegales")
                        .HasForeignKey("id_Expediente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("expediente");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.Expediente", b =>
                {
                    b.HasOne("Abogados_MiguelRojas_JURIDIBASE.Models.Caso", "caso")
                        .WithOne("expediente")
                        .HasForeignKey("Abogados_MiguelRojas_JURIDIBASE.Models.Expediente", "id_Caso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("caso");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.Notificacion", b =>
                {
                    b.HasOne("Abogados_MiguelRojas_JURIDIBASE.Models.Usuario", "usuario")
                        .WithMany("notificacion")
                        .HasForeignKey("id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.Pago", b =>
                {
                    b.HasOne("Abogados_MiguelRojas_JURIDIBASE.Models.Abogado", "abogado")
                        .WithMany("pago")
                        .HasForeignKey("idAbogado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Abogados_MiguelRojas_JURIDIBASE.Models.Cliente", "cliente")
                        .WithMany("pago")
                        .HasForeignKey("idCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Abogados_MiguelRojas_JURIDIBASE.Models.Caso", "caso")
                        .WithMany("pago")
                        .HasForeignKey("id_Caso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("abogado");

                    b.Navigation("caso");

                    b.Navigation("cliente");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.Abogado", b =>
                {
                    b.Navigation("abogadoArea");

                    b.Navigation("abogadoServicio");

                    b.Navigation("audiencia");

                    b.Navigation("caso");

                    b.Navigation("cita");

                    b.Navigation("cliente");

                    b.Navigation("pago");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.AreaDerecho", b =>
                {
                    b.Navigation("abogadoArea");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.Caso", b =>
                {
                    b.Navigation("audiencia");

                    b.Navigation("expediente")
                        .IsRequired();

                    b.Navigation("pago");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.Cliente", b =>
                {
                    b.Navigation("caso");

                    b.Navigation("cita");

                    b.Navigation("pago");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.Expediente", b =>
                {
                    b.Navigation("documentosLegales");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.ServicioLegal", b =>
                {
                    b.Navigation("abogadoServicio");
                });

            modelBuilder.Entity("Abogados_MiguelRojas_JURIDIBASE.Models.Usuario", b =>
                {
                    b.Navigation("abogado")
                        .IsRequired();

                    b.Navigation("notificacion");
                });
#pragma warning restore 612, 618
        }
    }
}
